import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { PNG } from 'pngjs';
import jsQR from 'jsqr';
import * as OTPAuth from 'otpauth';
import QRCode from 'qrcode';
import { makeTotp } from '../src/core.mjs';

const base = process.env.PREVIEW_URL || 'http://127.0.0.1:4173';
const secret = 'JBSWY3DPEHPK3PXP';
const now = 1234567890000;
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ headless: true });
const errors = [];
const remoteRequests = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!request.url().startsWith(base) && !request.url().startsWith('data:')) remoteRequests.push(request.url()); });
  await page.clock.install({ time: now });
  await page.clock.pauseAt(now);
  await page.goto(base);
  await page.locator('main').waitFor();
  await page.screenshot({ path: 'test-results/desktop-empty.png', fullPage: true });
  assert.equal(await page.locator('#secret').getAttribute('type'), 'password');
  assert.equal(await page.getByRole('button', { name: '生成二维码', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '获取验证码', exact: true }).click();
  assert.match(await page.locator('[role=alert]').innerText(), /请输入/);
  await page.locator('#secret').fill(' jbsw y3dp ehpk3pxp ');
  await page.locator('#secret').press('Enter');
  const expected = makeTotp(secret).generate({ timestamp: now });
  assert.equal((await page.locator('#token').innerText()).replace(/\s/g, ''), expected);
  await page.getByRole('button', { name: '显示密钥', exact: true }).click();
  assert.equal(await page.locator('#secret').getAttribute('type'), 'text');
  await page.getByRole('button', { name: '隐藏密钥', exact: true }).click();
  await page.getByRole('button', { name: '复制验证码', exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), expected);
  await page.getByRole('button', { name: '复制取码链接', exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), `${base}/2fa/${secret}`);
  await page.clock.runFor(30000);
  assert.equal((await page.locator('#token').innerText()).replace(/\s/g, ''), makeTotp(secret).generate({ timestamp: now + 30000 }));
  assert.equal(await page.locator('progress').getAttribute('value'), '30');
  await page.clock.setSystemTime(now + 125000);
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  assert.equal((await page.locator('#token').innerText()).replace(/\s/g, ''), makeTotp(secret).generate({ timestamp: now + 125000 }));
  await page.screenshot({ path: 'test-results/desktop-result.png', fullPage: true });

  await page.getByRole('button', { name: '生成二维码', exact: true }).click();
  await page.locator('#issuer').fill('测试 & GitHub');
  await page.locator('#account').fill('name+测试@example.com');
  await page.locator('.qr-image img').waitFor();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: '下载二维码', exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs('test-results/authenticator.png');
  const png = PNG.sync.read(await readFile('test-results/authenticator.png'));
  const qr = jsQR(new Uint8ClampedArray(png.data), png.width, png.height);
  const imported = OTPAuth.URI.parse(qr.data);
  assert.equal(imported.secret.base32, secret);
  assert.equal(imported.label, 'name+测试@example.com');
  assert.equal(imported.issuer, '测试 & GitHub');
  assert.equal(imported.generate({ timestamp: now }), expected);
  await page.screenshot({ path: 'test-results/desktop-qr.png', fullPage: true });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog[open]').count(), 0);

  await page.locator('#secret').fill('NOT-A-KEY');
  assert.equal(await page.locator('#token').innerText(), '--- ---');
  await page.getByRole('button', { name: '获取验证码', exact: true }).click();
  assert.equal(await page.locator('[role=alert]').isVisible(), true);
  for (const suffix of [`/#/${secret}`, `/?key=${secret}`, `/#secret=${secret}`]) {
    await page.goto(base + suffix);
    await page.waitForFunction(() => document.querySelector('#token')?.textContent.match(/\d{3} \d{3}/));
    assert.equal(new URL(page.url()).hash, '#/' + secret);
    assert.equal(new URL(page.url()).pathname, '/');
    assert.equal(new URL(page.url()).search, '');
  }
  await page.goto(`${base}/?digits=8&period=60&algorithm=SHA256#/${secret}`);
  await page.waitForFunction(() => document.querySelector('#token')?.textContent.match(/\d{4} \d{4}/));
  assert.equal(await page.locator('#digits').inputValue(), '8');
  const customToken = await page.locator('#token').innerText();
  await page.locator('#period').fill('0');
  assert.equal(await page.locator('#token').innerText(), '--- ---');
  await page.getByRole('button', { name: '获取验证码', exact: true }).click();
  assert.match(await page.locator('[role=alert]').innerText(), /刷新周期/);
  await page.goto(`${base}/#/%GG`);
  await page.locator('[role=alert]').waitFor();
  await page.goto(`${base}/#/${secret}`);
  await page.getByRole('button', { name: '清空', exact: true }).click();
  assert.equal(await page.locator('#secret').inputValue(), '');
  assert.equal(page.url(), base + '/');
  await page.reload();
  assert.equal(await page.locator('#secret').inputValue(), '');
  assert.deepEqual(await page.evaluate(() => ({ session: sessionStorage.length, cookie: document.cookie })), { session: 0, cookie: '' });
  assert.ok(await page.locator('.history-row').count() > 0);

  await page.locator('#qr-file').setInputFiles('test-results/authenticator.png');
  await page.waitForFunction(() => document.querySelector('#secret')?.value === 'JBSWY3DPEHPK3PXP');
  await page.getByRole('button', { name: '复制密钥', exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), secret);
  await page.getByRole('button', { name: '生成二维码', exact: true }).click();
  assert.equal(await page.locator('#issuer').inputValue(), '测试 & GitHub');
  assert.equal(await page.locator('#account').inputValue(), 'name+测试@example.com');
  await page.keyboard.press('Escape');
  const customQr = await QRCode.toBuffer(makeTotp(secret, { digits: 8, period: 60, algorithm: 'SHA256' }).toString());
  await page.locator('#qr-file').setInputFiles({ name: 'custom.png', mimeType: 'image/png', buffer: customQr });
  await page.waitForFunction(() => document.querySelector('#digits')?.value === '8');
  assert.equal(await page.locator('#period').inputValue(), '60');
  assert.equal(await page.locator('#algorithm').inputValue(), 'SHA256');
  const blank = new PNG({ width: 100, height: 100 });
  blank.data.fill(255);
  await page.locator('#qr-file').setInputFiles({ name: 'blank.png', mimeType: 'image/png', buffer: PNG.sync.write(blank) });
  await page.locator('[role=alert]').waitFor();
  assert.match(await page.locator('[role=alert]').innerText(), /未识别到二维码/);
  assert.equal(await page.locator('#secret').inputValue(), secret);
  const unrelatedQr = await QRCode.toBuffer('https://example.com/');
  await page.locator('#qr-file').setInputFiles({ name: 'ordinary.png', mimeType: 'image/png', buffer: unrelatedQr });
  await page.waitForFunction(() => document.querySelector('[role=alert]')?.textContent.includes('普通网址'));
  await page.locator('#qr-file').setInputFiles({ name: 'bad.png', mimeType: 'image/png', buffer: Buffer.from('not an image') });
  await page.waitForFunction(() => document.querySelector('[role=alert]')?.textContent.includes('无法打开'));

  for (const width of [390, 320, 768]) {
    await page.setViewportSize({ width, height: 844 });
    await page.goto(`${base}/?digits=8#/${secret}`);
    await page.waitForFunction(() => document.querySelector('#token')?.textContent.match(/\d{4} \d{4}/));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow ${width}`);
    const token = await page.locator('#token').boundingBox();
    const copy = await page.locator('.copy-token').boundingBox();
    assert.ok(token.x + token.width <= copy.x, `token overlap ${width}`);
    await page.screenshot({ path: `test-results/mobile-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: '生成二维码', exact: true }).click();
    await page.locator('.qr-image img').waitFor();
    const dialog = await page.locator('dialog[open]').boundingBox();
    assert.ok(dialog.x >= 0 && dialog.x + dialog.width <= width);
    await page.screenshot({ path: `test-results/qr-${width}.png`, fullPage: true });
    await page.keyboard.press('Escape');
  }
  await page.goto(base);
  const historyCount = await page.locator('.history-row').count();
  assert.ok(historyCount > 0);
  await page.getByRole('button', { name: '编辑历史信息', exact: true }).first().click();
  await page.locator('#history-issuer').fill('Tencent Cloud Services');
  await page.locator('#history-account').fill('100023184316');
  await page.locator('#history-note').fill('GitHub 主账号 <b>备注</b>');
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  assert.equal(await page.locator('.history-name').first().innerText(), 'Tencent Cloud Services · 100023184316');
  await page.locator('#secret').press('Enter');
  assert.equal(await page.locator('.history-name').first().innerText(), 'Tencent Cloud Services · 100023184316');
  assert.equal(await page.locator('.history-note').first().innerText(), 'GitHub 主账号 <b>备注</b>');
  assert.equal(await page.locator('.history-note b').count(), 0);
  await page.reload();
  assert.equal(await page.locator('.history-name').first().innerText(), 'Tencent Cloud Services · 100023184316');
  assert.equal(await page.locator('.history-note').first().innerText(), 'GitHub 主账号 <b>备注</b>');
  await page.getByRole('button', { name: '使用此历史记录取码' }).first().click();
  assert.equal(await page.locator('.history-note').first().innerText(), 'GitHub 主账号 <b>备注</b>');
  await page.getByRole('button', { name: '编辑历史信息', exact: true }).first().click();
  await page.locator('#history-note').fill('不保存');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  assert.equal(await page.locator('.history-note').first().innerText(), 'GitHub 主账号 <b>备注</b>');
  await page.getByRole('button', { name: '编辑历史信息', exact: true }).first().click();
  await page.locator('#history-note').fill('');
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  assert.equal(await page.locator('.history-note').count(), 0);
  assert.equal(await page.locator('#secret').inputValue(), secret);
  assert.equal(await page.locator('.history-row').count(), historyCount);
  await page.getByRole('button', { name: '显示历史密钥', exact: true }).click();
  assert.match(await page.locator('.history-secret').first().innerText(), new RegExp(secret));
  await page.getByRole('button', { name: '隐藏历史密钥', exact: true }).click();
  assert.ok(!(await page.locator('.history-secret').first().innerText()).includes(secret));
  await page.getByRole('button', { name: '删除此历史记录' }).first().click();
  assert.equal(await page.locator('.history-row').count(), historyCount - 1);
  await page.getByRole('button', { name: '清空历史', exact: true }).click();
  await page.getByRole('button', { name: '取消', exact: true }).click();
  assert.equal(await page.locator('.history-row').count(), historyCount - 1);
  await page.getByRole('button', { name: '清空历史', exact: true }).click();
  await page.getByRole('button', { name: '确认清空', exact: true }).click();
  assert.equal(await page.locator('.history-row').count(), 0);
  await page.reload();
  assert.equal(await page.locator('.history-row').count(), 0);
  await page.getByLabel('记录本次使用').uncheck();
  await page.locator('#secret').fill(secret);
  await page.locator('#secret').press('Enter');
  assert.equal(await page.locator('.history-row').count(), 0);
  await page.getByLabel('记录本次使用').check();
  await page.locator('#secret').press('Enter');
  assert.equal(await page.locator('.history-row').count(), 1);
  await page.reload();
  assert.equal(await page.locator('.history-row').count(), 1);
  await page.setViewportSize({ width: 320, height: 700 });
  await page.getByRole('button', { name: '编辑历史信息', exact: true }).first().click();
  const editDialog = await page.locator('dialog[open]').boundingBox();
  assert.ok(editDialog.x >= 0 && editDialog.x + editDialog.width <= 320);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.keyboard.press('Escape');

  const stored = await page.evaluate(() => localStorage.getItem('twofa.history.v1'));
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(`${base}/2fa/${secret}?digits=8&period=60&algorithm=SHA256`);
    await page.locator('.direct-token').waitFor();
    assert.equal(new URL(page.url()).pathname, '/2fa/' + secret);
    assert.equal(await page.locator('.site-header').isVisible(), false);
    assert.equal(await page.locator('.history').isVisible(), false);
    const timestamp = await page.evaluate(() => Date.now());
    const code = makeTotp(secret, { digits: 8, period: 60, algorithm: 'SHA256' }).generate({ timestamp });
    assert.equal(await page.locator('.direct-token').innerText(), code);
    await page.locator('.direct-token').click();
    assert.equal(await page.evaluate(() => navigator.clipboard.readText()), code);
    await page.clock.runFor(60000);
    assert.equal(await page.locator('.direct-token').innerText(), makeTotp(secret, { digits: 8, period: 60, algorithm: 'SHA256' }).generate({ timestamp: timestamp + 60000 }));
    assert.equal(await page.evaluate(() => localStorage.getItem('twofa.history.v1')), stored);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: `test-results/direct-${width}.png`, fullPage: true });
  }
  await page.goto(`${base}/2fa/INVALID!`);
  await page.locator('.direct-page [role=alert]').waitFor();
  assert.equal(await page.locator('.direct-token').count(), 0);
  await page.getByRole('link', { name: '返回首页' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/history-mobile.png', fullPage: true });
  await page.evaluate(() => localStorage.setItem('twofa.history.v1', '{'));
  await page.reload();
  await page.locator('.history [role=alert]').waitFor();
  await page.getByRole('button', { name: '清空历史', exact: true }).click();
  await page.getByRole('button', { name: '确认清空', exact: true }).click();
  assert.equal(await page.locator('.history [role=alert]').count(), 0);
  const blocked = await context.newPage();
  await blocked.addInitScript(() => {
    Storage.prototype.setItem = () => { throw new Error('Storage denied'); };
  });
  await blocked.goto(base);
  await blocked.locator('#secret').fill(secret);
  await blocked.locator('#secret').press('Enter');
  await blocked.locator('.history [role=alert]').waitFor();
  assert.match(await blocked.locator('#token').innerText(), /\d{3} \d{3}/);
  await blocked.close();
  assert.deepEqual(errors, []);
  assert.deepEqual(remoteRequests, []);
  console.log('Browser checks passed: generation, rollover, copy, QR import/export, direct pages, local history, persistence/errors/deletion, no external requests, desktop/mobile layouts.');
  console.log(`Custom token rendered: ${customToken}`);
  await context.close();
} finally {
  await browser.close();
}
